### ISSUE TITLE
Split the existing Readme into Contributing.md 

### ISSUE THREAD

**Issue by sunnysetia93** [sunnysetia93/browser-based-file-system-MERN#2]
Need to move a few bullet points regarding project setup and collaborations to a separate **_Contributing.md_** file.

**Raise a PR.**

**Comment by geekysrm** [comment]
Can I work on this @sunnysetia93 ?

**Comment by sunnysetia93** [comment]
Sure @geekysrm

**Comment by geekysrm** [comment]
Done @sunnysetia93 ! :) https://github.com/sunnysetia93/browser-based-file-system-MERN/pull/5

**Comment by sunnysetia93** [comment]
Merged. Thanks man.
